//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planesia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adminDB
    {
        public int adminId { get; set; }
        public string adminName { get; set; }
        public string adminUsername { get; set; }
        public string adminPassword { get; set; }
        public byte[] adminPhoto { get; set; }
        public string adminPhone { get; set; }
        public string adminEmail { get; set; }
        public string adminCity { get; set; }
    }
}
