//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planesia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distribution
    {
        public int DistributionArea { get; set; }
        public Nullable<double> DistributionLongitude { get; set; }
        public Nullable<double> DistributionLatitude { get; set; }
    }
}
