//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planesia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flora
    {
        public int FloraId { get; set; }
        public string FloraName { get; set; }
        public string FloraLatinName { get; set; }
        public Nullable<System.DateTime> FloraDate { get; set; }
        public string FloraDistribution { get; set; }
        public string FloraDiscoverer { get; set; }
        public string FloraOtherDescription { get; set; }
        public string FloraPhoto { get; set; }
        public Nullable<int> UserId { get; set; }
        public string FloraStatus { get; set; }
    
        public virtual User User { get; set; }
    }
}
