//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planesia.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlanesiaDBsEntities : DbContext
    {
        public PlanesiaDBsEntities()
            : base("name=PlanesiaDBsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Campaign> Campaigns { get; set; }
        public virtual DbSet<Distribution> Distributions { get; set; }
        public virtual DbSet<Fauna> Faunas { get; set; }
        public virtual DbSet<Flora> Floras { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
