//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planesia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userDB
    {
        public int userId { get; set; }
        public string userName { get; set; }
        public string userPassword { get; set; }
        public byte[] userPhoto { get; set; }
        public string userPhone { get; set; }
        public string userEmail { get; set; }
        public string userCity { get; set; }
    }
}
